services:
  - type: web
    name: yared-portfolio-backend
    runtime: docker
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Set this in the Render Dashboard securely
      - key: TELEGRAM_CHAT_ID
        sync: false # Set this in the Render Dashboard securely
